'use client';
import { useMemo, useState } from 'react';
import { Activity, ArrowDownToLine, ArrowUpRight, CalendarDays, ChevronLeft, ChevronRight, Flag, Footprints, LayoutDashboard, Medal, Search, Timer, Trophy, Users, Zap } from 'lucide-react';
import { summarize } from '@/application/get-dashboard';
import { paceLabel, type Run } from '@/domain/running';
const number = (n: number) => n.toLocaleString('id-ID', { maximumFractionDigits: 2 });
const dateLabel = (d: string) => new Date(d+'T00:00:00').toLocaleDateString('id-ID', {day:'numeric', month:'short'});
export function Dashboard({ runs, lastUpdated }: { runs: Run[]; lastUpdated: string }) {
  const dates = runs.map(r=>r.date).sort();
  const [start,setStart] = useState(dates[0] ?? ''); const [end,setEnd] = useState(dates.at(-1) ?? '');
  const [search,setSearch] = useState(''); const [tab,setTab] = useState('overview'); const [page,setPage] = useState(0);
  const filtered = useMemo(()=>runs.filter(r=>(!start || r.date>=start)&&(!end || r.date<=end)&&r.name.toLowerCase().includes(search.toLowerCase())),[runs,start,end,search]);
  const stats = useMemo(()=>summarize(filtered),[filtered]);
  const recent = [...filtered].sort((a,b)=>b.date.localeCompare(a.date) || b.distance-a.distance);
  const max = Math.max(...stats.daily.map(([,d])=>d),1);
  const resetPage = () => setPage(0);
  function exportCsv() {
    const csv = '\uFEFFNama;Tanggal;Jarak (km);Durasi (detik);Pace (menit/km)\n'+filtered.map(r=>[r.name,r.date,r.distance,r.seconds,paceLabel(r.seconds,r.distance)].join(';')).join('\n');
    const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})); const a=document.createElement('a'); a.href=url; a.download='aktivitas-lari.csv'; a.click(); URL.revokeObjectURL(url);
  }
  return <div className="shell"><aside className="sidebar"><a className="brand" href="/"><span className="brand-icon"><img src="/bs-gold.png" alt="Logo Bridgestone gold"/></span><span>BSCup Running Challenges<small>Bridgestone - Bekasi Plant</small></span></a><div className="side-label">WORKSPACE</div><nav>{[{id:'overview',label:'Overview',icon:LayoutDashboard},{id:'leaderboard',label:'Klasemen',icon:Trophy},{id:'activities',label:'Aktivitas lari',icon:Activity}].map(({id,label,icon:Icon})=><button key={id} className={tab===id?'selected':''} onClick={()=>{setTab(id);resetPage()}}><Icon size={18}/>{label}{tab===id&&<span className="nav-dot"/>}</button>)}</nav><div className="side-event"><Flag size={22}/><small>BEKASI PLANT</small><h3>Every step.<br/>One spirit.</h3><p>Bergerak bersama, melangkah lebih jauh.</p><span>CUP 2026 <ArrowUpRight size={14}/></span></div><div className="sidebar-bottom"><span className="avatar">BP</span><div>Bridgestone Cup<small>Employee wellbeing program</small></div></div></aside>
  <main><header className="topbar"><div className="breadcrumb">Workspace <span>/</span> <b>{tab==='overview'?'Overview':tab==='leaderboard'?'Klasemen':'Aktivitas lari'}</b></div><div className="top-right"><span className="status-dot"/> Last updated: {lastUpdated} <span className="avatar">BP</span></div></header><div className="content"><div className="page-heading"><div><div className="eyebrow">BRIDGESTONE CUP BEKASI PLANT 2026</div><h1>{tab==='overview'?'Running dashboard':tab==='leaderboard'?'Klasemen pelari':'Aktivitas lari'}<span>.</span></h1><p>Setiap kilometer berarti. Lihat perjalanan dan pencapaian kita bersama.</p></div><button className="export" onClick={exportCsv}><ArrowDownToLine size={16}/> Ekspor data</button></div>
  <section className="hero"><div className="hero-copy"><span className="hero-tag"><span/> EMPLOYEE WELLBEING PROGRAM</span><h2>ONE TEAM.<br/><em>MORE MILES.</em></h2><p>Semangat kompetisi, langkah penuh energi.<br/>Bersama menuju versi terbaik diri kita.</p><div className="hero-bottom"><span><Flag size={14}/> BEKASI PLANT</span><span className="hero-year">SEASON 2026</span></div></div><div className="track-art" aria-hidden="true"><div className="track-lines"><i/><i/><i/><i/></div><div className="track-number">26</div><Footprints className="track-foot" size={62}/></div><div className="hero-summary"><small>TOTAL JARAK TERKUMPUL</small><strong>{number(stats.distance)}<span> km</span></strong><span className="hero-summary-caption">{stats.athletes.length} pelari · satu semangat</span></div></section>
  <div className="filterbar"><div><CalendarDays size={16}/><b>Periode aktivitas</b></div><div className="dates"><input aria-label="Tanggal mulai" type="date" value={start} onChange={e=>{setStart(e.target.value);resetPage()}}/><span>—</span><input aria-label="Tanggal akhir" type="date" value={end} onChange={e=>{setEnd(e.target.value);resetPage()}}/><button onClick={()=>{setStart(dates[0]??'');setEnd(dates.at(-1)??'');setSearch('');resetPage()}}>Reset</button></div></div>{start>end&&<p className="notice">Tanggal mulai harus sebelum tanggal akhir.</p>}
  <section className="metrics">{[{label:'Total jarak',value:number(stats.distance),unit:'km',sub:'Akumulasi seluruh aktivitas',icon:Footprints},{label:'Pelari aktif',value:number(stats.athletes.length),unit:'orang',sub:'Melangkah bersama dalam periode ini',icon:Users},{label:'Total aktivitas',value:number(filtered.length),unit:'sesi',sub:'Setiap langkah tercatat',icon:Zap},{label:'Rata-rata pace',value:paceLabel(stats.seconds,stats.timedDistance),unit:'/km',sub:'Dihitung dari durasi dan jarak valid',icon:Timer}].map(({label,value,unit,sub,icon:Icon})=><article className="metric" key={label}><div>{label}<Icon size={18}/></div><strong>{value} <small>{unit}</small></strong><p>{sub}</p></article>)}</section>
  {tab==='overview'&&<section className="charts-grid"><article className="panel chart-panel"><div className="panel-heading"><div><h3>Jarak harian</h3><p>Konsistensi kecil, pencapaian besar.</p></div><span className="legend"><i/> Jarak (km)</span></div>{stats.daily.length?<div className="chart"><div className="chart-y">{[1,.75,.5,.25,0].map(x=><span key={x}>{Math.round(max*x)}</span>)}</div><div className="plot"><div className="gridlines"><i/><i/><i/><i/><i/></div><div className="bars">{stats.daily.map(([date,distance])=><div className="bar-column" key={date}><div className="bar" style={{height:`${Math.max(distance/max*100,2)}%`}} tabIndex={0} aria-label={`${dateLabel(date)}: ${number(distance)} km`}><span className="bar-tooltip">{number(distance)} km</span></div><small>{dateLabel(date)}</small></div>)}</div></div></div>:<div className="empty">Tidak ada aktivitas untuk filter ini.</div>}<div className="chart-footer"><Activity size={15}/> {stats.daily.length} hari aktif <span>Total {number(stats.distance)} km</span></div></article><article className="panel podium"><div className="panel-heading"><div><h3><Trophy size={17}/> Pelari teratas</h3><p>Jarak terjauh, semangat luar biasa.</p></div><span className="badge">TOP 3</span></div>{stats.athletes.slice(0,3).map((a,i)=><div className={'top-runner rank-'+i} key={a.name}><span className="rank">{i===0?<Medal size={22}/>:String(i+1).padStart(2,'0')}</span><div><b>{a.name}</b><small>{a.count} aktivitas · {paceLabel(a.seconds,a.timedDistance)} /km</small></div><strong>{number(a.distance)}<small>km</small></strong></div>)}{!stats.athletes.length&&<div className="empty">Belum ada pelari.</div>}<button className="view-all" onClick={()=>{setTab('leaderboard');resetPage()}}>Lihat semua klasemen <ArrowUpRight size={16}/></button></article></section>}
  <section className="panel table-panel"><div className="panel-heading"><div><h3>{tab==='leaderboard'?'Klasemen lengkap':'Aktivitas terbaru'}</h3><p>{tab==='leaderboard'?'Diurutkan berdasarkan total jarak.':'Catatan langkah dari seluruh pelari.'}</p></div><label className="search"><Search size={16}/><input placeholder="Cari nama pelari..." aria-label="Cari nama pelari" value={search} onChange={e=>{setSearch(e.target.value);resetPage()}}/></label></div><div className="table-scroll"><table><thead><tr><th>{tab==='leaderboard'?'PERINGKAT':'PELARI'}</th><th>{tab==='leaderboard'?'PELARI':'TANGGAL'}</th><th>JARAK <span>(KM)</span></th><th>{tab==='leaderboard'?'AKTIVITAS':'DURASI'}</th><th>PACE <span>(/KM)</span></th><th>STATUS</th></tr></thead><tbody>{tab==='leaderboard'?stats.athletes.slice(page*8,page*8+8).map((a,i)=><tr key={a.name}><td><span className="table-rank">#{page*8+i+1}</span></td><td><div className="runner-cell"><span className="initial">{a.name.slice(0,2).toUpperCase()}</span>{a.name}</div></td><td className="distance">{number(a.distance)}</td><td>{a.count} sesi</td><td>{paceLabel(a.seconds,a.timedDistance)}</td><td><span className="activity-badge">Aktif</span></td></tr>):recent.slice(page*8,page*8+8).map(r=><tr key={r.id}><td><div className="runner-cell"><span className="initial">{r.name.slice(0,2).toUpperCase()}</span>{r.name}</div></td><td>{dateLabel(r.date)} {r.date.slice(0,4)}</td><td className="distance">{number(r.distance)}</td><td>{r.seconds?`${Math.floor(r.seconds/3600).toString().padStart(2,'0')}:${Math.floor(r.seconds%3600/60).toString().padStart(2,'0')}:${(r.seconds%60).toString().padStart(2,'0')}`:'—'}</td><td>{paceLabel(r.seconds,r.distance)}</td><td><span className={r.seconds?'activity-badge':'activity-badge muted'}>{r.seconds?'Tercatat':'Tanpa durasi'}</span></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">Tidak ada hasil. Coba ubah pencarian atau periode tanggal.</div>}</div><div className="pagination"><span>Menampilkan {filtered.length?page*8+1:0}–{Math.min((page+1)*8,tab==='leaderboard'?stats.athletes.length:recent.length)} dari {tab==='leaderboard'?stats.athletes.length:recent.length} {tab==='leaderboard'?'pelari':'aktivitas'}</span><div><button aria-label="Halaman sebelumnya" disabled={!page} onClick={()=>setPage(page-1)}><ChevronLeft size={16}/></button><span>{page+1}</span><button aria-label="Halaman berikutnya" disabled={(page+1)*8>=(tab==='leaderboard'?stats.athletes.length:recent.length)} onClick={()=>setPage(page+1)}><ChevronRight size={16}/></button></div></div></section>
  {stats.missingDuration>0&&<p className="data-note">{stats.missingDuration} aktivitas tanpa durasi tetap dihitung dalam total jarak; tidak disertakan dalam rata-rata pace.</p>}<footer><span>RUN CLUB <b> / </b> BRIDGESTONE CUP BP 2026</span><span>Data lokal · {dateLabel(dates.at(-1)??'2026-09-18')} 2026</span></footer></div></main></div>
}
